### ISSUE TITLE
[Feature Request] Further control over CFG and Denoising 

### ISSUE THREAD

**Issue by guzuligo** [tkalayci71/attenuate-cfg-scale#1]
I'd like to share the same idea here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4566

The idea is to have another choice for advance modification of CFG and possibly Denoising and other parameters as well.
The user could input on which step he wants the CFG and denoising to change and to what value. Possibly through an array of numbers including the step and new value on that step.

Also, instead of being limited with CFG on 30, allow the script to override the value and go limitless.

From my experimentation, letting denoise work a bit before spiking the CFG again could result in adding  details over a better image, and possibly adding the features at the right time using prompt editing.

**Comment by guzuligo** [comment]
Updated my code with your new code, and glad to share it 😁👍
https://github.com/guzuligo/CFG-Schedule-for-Automatic1111-SD

**Comment by tkalayci71** [comment]
Hey I just tried your latest version, looking good, getting interesting results. It's certainly much more flexible than mine (I didn't even know you could eval a string in python). By the way, the syntax is a bit complicated, more examples would be nice (even plotting a graph maybe) Also I'm not even sure what ETA does and which samplers support it (I'm new to many things you see). I will experiment more, thanks for sharing!

**Comment by guzuligo** [comment]
I didn't notice your reply 😅

Glad you find it useful. I am new myself to many things. Actually, wouldn't be able to do it without your help 👍

I'm not sure exactly what ETA does. But, try making it 10 or 100 and you'll notice its effect. Some kind of noise?? Not sure. But it has strong effect on result.

The one I wish I could really change is the denoising. I couldn't find a way to change it as it is the thing that has the strongest effect on final results.

There is also a new update now. It seems using index of samples is no longer possible after the last one.
